language: node_js
node_js:
  - '14'
before_install:
  - npm i -g npm@latest

  # Needed for Karma test runner
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - yarn
script:
  - yarn lint
  - yarn test
after_success:
  - yarn run codecov
notifications:
  slack:
    secure: kAmrLltV0ZLuhl6rKk26fDLGuoCch6AYaObRQje4UZlxVQjR2467k430vOZLqv39Mr3U5XmYl6VLcCGmBr3tjM/9c1zjoXnRT8MRy4eIYaUr/thXeh2FlfHKOk8rXnNOoRZ1kBsCzCDFCNDYZZA4jya8S5ITcQyGyYcOqBWVy1w=
cache: yarn
